### ISSUE TITLE
Zero-initialized aligned reallocation

### ISSUE THREAD

**Issue by pitrou** [microsoft/mimalloc#133]
mimalloc provides a non-trivial set of allocation options:
- aligned
- zero-initialized
- reallocation
- aligned reallocation
- zero-initialized reallocation

However, according to the [docs](https://microsoft.github.io/mimalloc/group__aligned.html) it doesn't seem to provide zero-initialized aligned reallocation. Is it an oversight?

We're going to investigate the suitability of mimalloc for use in Apache Arrow and this is a feature that would be useful to us.

**Comment by daanx** [comment]
Ah, I used to have it but as discussed in issue #63, we decided to drop it.

The reason is that zero-initialized reallocation only works when the original memory was allocated with `calloc` or `zalloc` and not with `malloc` . In the latter case, since mimalloc does not keep track of the original allocation in bytes, it is not possible to know on reallocation where the zero-initialization starts. So, generally it works but there are edge cases where it can lead to subtle bugs.....

I think this is why it is not part of Posix, and perhaps it is better to have the programmer initialize to zero explicitly when reallocating.

**Comment by daanx** [comment]
(btw, the function `mi_recalloc` is still exposed though... even though it has this unsafe behaviour..)

**Comment by pitrou** [comment]
> The reason is that zero-initialized reallocation only works when the original memory was allocated with calloc or zalloc and not with malloc .

Well, that sounds like a reasonable limitation to me.

> I think this is why it is not part of Posix, and perhaps it is better to have the programmer initialize to zero explicitly when reallocating.

Isn't there a performance issue with this? If `mimalloc` allocates using mmap(), it knows the memory is already zero-initialized. The caller doesn't, and will call `memset` even when not needed.

POSIX doesn't have aligned reallocation either... but mimalloc does.

**Comment by pitrou** [comment]
Also, for the record, jemalloc does support zero-initialized aligned reallocation through its `flags` argument to `rallocx`: http://jemalloc.net/jemalloc.3.html

So there's precedent for exposing such a feature.

**Comment by pitrou** [comment]
Hmm, I took a look, and it seems that mimalloc zero-initialization blindly calls `memset` instead of taking advantage of page zeroing by the OS. So perhaps there isn't much performance advantage in having zero-initialized allocation functions.

**Comment by daanx** [comment]
Hi Pitrou,

I just pushed commit dev a6a956c  which adds back the zero-initialized reallocation api. Moreover, the new commit builds on earlier changes that detect if the memory is already zero-initialized on `calloc` etc to avoid using memset to zero.  Hope this works for Apache Arrow -- let me know how it goes.

**Comment by pitrou** [comment]
To be clear, we aren't zero-initializing yet and this is a feature that we would like to investigate in the future (depending largely on its cost, I guess). But thanks for reintegrating those functions.

**Comment by daanx** [comment]
Thanks @pitrou , no worries. It seems a good API to have as long as one is aware of the gotcha so I put extra comments in the header file.

**Comment by gnzlbg** [comment]
> The reason is that zero-initialized reallocation only works when the original memory was allocated with calloc or zalloc

I think this is a reasonable restriction. 

Instead of wording this comment as a warning, I think it would be better to word it more precisely as a guarantee. For example, we can say that if and only if the realloc grows the `usable_size` of the allocation to a `new_usable_size > usable_size`, the the range `new_usable_size - usable_size` will be zeroed. If the realloc does not grow the `usable_size` of the allocation, it has no effects.

That is, if one allocates with `malloc(request)` and obtains an allocation with `usable_size`, and then performs a zero-reallocation that doesn't modify the `usable_size`, then because there are no effects the range `usable_size - request` won't be zeroed.

>  In the latter case, since mimalloc does not keep track of the original allocation in bytes, it is not possible to know on reallocation where the zero-initialization starts. So, generally it works but there are edge cases where it can lead to subtle bugs.....

I don't know if there is space in any meta-data bitset anywhere to add a bit tracking this on a per allocation basis for debugging / checked build purposes, but I don't think we can be 100% certain that when this happen there is a bug in the user code, so we can at most only warn here.

**Comment by daanx** [comment]
@gnzlbg: good suggestion -- I will add that to the documentation.
