### ISSUE TITLE
"cannot allocate memory in static TLS block"

### ISSUE THREAD

**Issue by pitrou** [microsoft/mimalloc#147]
Take this bug report with a grain of salt, but when enabling mimalloc (note: not _using_ it, just linking our `.so` with it) some of our CI builds fail deterministically with a "cannot allocate memory in static TLS block" error.

I also know that jemalloc faced a similar issue and provided a build-time option to work around it.  It happens in the cases where jemalloc or the jemalloc-containing library (in case jemalloc was statically linked) is loaded lazily using `dlopen`. This seems to correspond exactly to the cases where we get the aforementioned error.

(amusingly, we were the ones reporting the jemalloc error already :-))

Here is the jemalloc report and discussion:
https://github.com/jemalloc/jemalloc/issues/937
Here is the fix committed to jemalloc. It seems to consist in an additional option that disables `-ftls-model=initial-exec`:
https://github.com/jemalloc/jemalloc/pull/1180/files

**Comment by daanx** [comment]
Darn, mimalloc has just 2 thread local variables, one for the default heap for that thread, and one for the recursion guard. I was hoping that would avoid this error. Is it possible for you try this with commenting out the `static mi_decl_thread bool recurse = false;` in `options.c` (just make it static for the test). I wonder if requiring just one slot makes a difference.

I am working currently also on fixing the TLS recursion guard on Apple (and some BSD) systems so perhaps I will add another way than requiring initial-exec. (Also, it seems building with `-ftls-model=gnu2` instead of `-ftls-model=initial-exec` may work too.)

**Comment by daanx** [comment]
Just wanted to add that using `-ftls-model=local-dynamic` should also work and seems to add almost no overhead; maybe 2% in my tests.

**Comment by pitrou** [comment]
It seems that `-ftls-model=local-dynamic` would fix the issue, at least according to my local tests.

**Comment by pitrou** [comment]
`static bool recurse = false;` doesn't seem to work, though (I still get the TLS-related error).

**Comment by pitrou** [comment]
And `gnu2` isn't recognized here (gcc 7.4.0, Ubuntu 18.04):
```
gcc-7: error: unknown TLS model ‘gnu2’
gcc-7: note: valid arguments to ‘-ftls-model=’ are: global-dynamic initial-exec local-dynamic local-exec
```

**Comment by daanx** [comment]
Good to hear -- `-ftls-model=local-dynamic` seems the proper solution for this. Maybe we can make it a build option.

**Comment by pitrou** [comment]
I opened https://github.com/microsoft/mimalloc/pull/148.
