### ISSUE TITLE
Leaking with Transmission

### ISSUE THREAD

**Issue by poige** [microsoft/mimalloc#163]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/600779/67396894-9009a800-f5d2-11e9-8ac9-9cc11f793732.png">

— as I [already](https://github.com/microsoft/mimalloc/issues/21#issuecomment-543274296) said.

I've made a test setup which loops torrent download — same torrent is being downloaded from one VM to another, then it's deleted, cycle repeats.

**Comment by poige** [comment]
That's how memory consumption changes (grows) with each new iteration (RSS VSZ):

```
66360 754912
83996 777564
93148 777564
112144 777560
125820 777560
138072 777560
147836 777560
160540 777560
174724 777560
190788 777560
202380 777560
202972 777560
214288 777560
222672 777560
227184 777560
237764 1039704
248436 1039704
262356 1039704
309348 1039704
329700 1039704
341652 1039704
357228 1039704
356800 1039704
369380 1039704
370316 1039704
382920 1039704
387960 1039704
399736 1039704
411656 1039704
420940 1039704
```

**Comment by daanx** [comment]
Thank you Oleg -- very interesting and we should fix it! Is there any way you can provide the source code so I can reproduce this locally? Is it possible to make the program smaller while the leak persists? (e.g. can we simulate the torrent download or something?).  

However, even just an executable so that I can repro is also good although that makes it much harder to find the problem of course.

**Comment by poige** [comment]
> is there any way you can provide the source code so I can reproduce this locally

I didn't use Transmission in sources, it's Ubuntu 18.04 binaries with ld.so.preload'ed mimalloc.

**Comment by poige** [comment]
> makes it much harder to find the problem of course.

May be you should think of solving it in more general way? Like, adding some debugging tools into allocator itself.

**Comment by daanx** [comment]
Thanks Oleg -- ah, just binary is ok too; I am running Ubuntu too -- can you give me specific instructions on how to reproduce this so I can try to figure out what is happening.  Best, Daan

**Comment by poige** [comment]
Just start Transmission-GTK loaded with a popular torrent. Fresh Ubuntu might be a good choice for that. Let it work for a while. To better see the difference it might be helpful to have same setup but w/o mimalloc preloading and compare theirs mem. usage at same time intervals.

**Comment by Thordin** [comment]
I'm also getting a memory leak for srcds_linux tf2 which does not leak when using jemalloc.

System is Ubuntu 18.04 x64, mimalloc version https://github.com/microsoft/mimalloc/commit/e05a1edc038477574ee5c1e4ea00f0a7b9ab9e67 compiled for 32bit.

Install with these instructions https://wiki.teamfortress.com/wiki/Linux_dedicated_server#Step-By-Step

Type **tf_bot_join_after_player 0;tf_bot_quota 16**

Wait a few seconds for the bots to join, type **changelevel ctf_2fort**. Virtual and real memory will increase every time you do this while it does not leak with jemalloc.

**Comment by daanx** [comment]
Thanks @Thordin. This seems to be the same problem as issue #177. It is the main thing I would like to fix but so far I cannot reproduce it locally, nor does it occur in any benchmark or other (super) large services that I test on. I have a feeling it happens when lots of threads are created / destroyed but `test-stress.c` creates/destroys many threads with objects surviving multiple generations and it works fine. So not sure. 

I looked at the instructions at your link but it seems a bit of work to get this going; is it perhaps possible for you to try out a potential fix first on your machine? The `dev-abandon` branch may potentially fix the leak and if you can build that and try that would be great. Let me know.

**Comment by poige** [comment]
>  I cannot reproduce it locally

I doubt this. Installing Ubuntu and Transmission there isn't a big deal even for Linux newbies.

**Comment by Thordin** [comment]
> cmake ../.. -DMI_DEBUG_FULL=ON

```
Running tests...
Test project /home/admin/mimalloc/out/debug
    Start 1: test_api,
1/2 Test #1: test_api, ........................***Failed    0.00 sec
    Start 2: test_stress,
2/2 Test #2: test_stress, .....................***Exception: SegFault 16.89 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =  16.90 sec

The following tests FAILED:
          1 - test_api, (Failed)
          2 - test_stress, (SEGFAULT)
Errors while running CTest
Makefile:129: recipe for target 'test' failed
make: *** [test] Error 8
```

Seems to leak more slowly, but still uses 25% more memory than jemalloc after 2 hours.

**Comment by daanx** [comment]
@Thordin: thanks for trying this! When you say "more slowly" does that mean it still leaks every time you issue the changelevel command? Or is it just using more memory now?   (A leak should be fixed for sure as that would be always increasing -- using more memory might be due to fragmentation etc but is essentially a different issue. )

In the meantime I added various improvements to `dev-abandon`; if you can try again and see how it does that would be great. Thanks again!

**Comment by daanx** [comment]
@Thordin: just in case you feel like trying again, the latest `dev-abandon` has some more subtle fixes (and `dev` too) that may fix the leaking issues.

**Comment by poige** [comment]
Closed due to fixed or just closed away? O_o

**Comment by daanx** [comment]
ah, just closed away but I will re-open it. I think the latest updates to `mimalloc`, (latest `dev` branch) contains various fixes and I was hoping that would fix the issue.  

I really want to make mimalloc work as best as possible across workloads so if you still see this problem we should really fix it and figure out what is the cause of this.

If you still see problems in the latest version, please give me more detailed instructions on how to reproduce it. I am not familiar with `transmission` (and hesitant to run a server or pull arbitrary content) so I need enough detail to make it work without needing to read manuals. I hope you understand. Best, Daan

**Comment by poige** [comment]
Yep, I understand that you're trying to present it so that using a simple torrent client to download, say, officially distributed Ubuntu image is too complex task to you.
