### ISSUE TITLE
is_zero is always false?

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/mimalloc#186]
https://github.com/microsoft/mimalloc/blob/master/src/os.c#L624

According to the implementation, `is_zero` is always false here. So, what is its correct usage?

**Comment by daanx** [comment]
Thanks for spotting this -- however, the idea is that both allocation and commit return in `is_zero` whether the memory is zero'd after that. It turns out that on all current platforms committing does not always zero out the memory. I believed at first that Windows does do that, but if you commit already committed memory it leaves it as is (of course!).  So for now, `is_zero` is always false for a commit. 

However, perhaps we should remove the parameter then, as there is no good reason to have it for commit...
