### ISSUE TITLE
overhead on allocations with empty page?

### ISSUE THREAD

**Issue by gamemachine** [microsoft/mimalloc#187]
I'm testing this via C# pinvoke FYI but I don't think that has anything to do here other then just general extra overhead.  Also this is using mimalloc directly not the overrides.  We are linking the static lib into our own dll which we call from C#.

when doing some quick benchmarks  mimalloc was doing really bad, like Marshal.AllocHGlobal was beating it by a significant margin.  On a hunch I did an allocation before the bench freeing it afterwards, so there was always something allocated during the test run.  And sure enough that was it.   Does this have something to do with constantly flipping between an empty page and one with allocations?

**Comment by daanx** [comment]
Thank you for spotting this -- indeed, for allocations over 256 bytes there is no caching of pages so doing one allocation followed by a free repeatedly will always take the slow allocation path :-(  We need  to fix this --  I used to have a page cache in a early design but removed it in the name of simplification (and since no benchmark was affected by it) but clearly we need to have it for cases like yours. Hope to get to it soon. (but your workaround will work -- just allocate something of the right size class for the duration of the program)

**Comment by daanx** [comment]
Should be fixed with  commit 2b108c8. Thanks!
