### ISSUE TITLE
Huge memory leak when working with 30 concurrent threads with mimalloc

### ISSUE THREAD

**Issue by lahavy** [microsoft/mimalloc#190]
I am using a 3rd party software which causes memory fragmentation (I have measured and malloc operation gets > x20 slower over time).
Replacing std::malloc with mimalloc fixed this issue, allocation is very fast, however my process memory is getting higher over time (it started with 30GB and rises to 90GB after one day).

**Comment by daanx** [comment]
Ouch! This problem has been reported before but I have not yet found the cause. Can you:

1. Build mimalloc from the latest `dev-abandon` branch and try with that. Over the last week I have made various fixes that may solve the issue.
2. If that does not work, can you provide me with detailed instructions to reproduce this locally? Not sure if you can since you are using 3rd party software?

Let me know if you can try this (and how it goes).

**Comment by lahavy** [comment]
1. Latest dev-abandon branch produces even higher leaks.... memory rises from 20 GB to 102 GB over night.
2. Sorry that can't provide source code to reproduce this issue

Thanks,
Lahav

**Comment by daanx** [comment]
Darn, I was hoping the latest fixes would solve this issue. As a further test, can you try the latest `dev` branch as well, but run with the environment variable `MIMALLOC_PAGE_RESET=1` ?  Thanks!

**Comment by daanx** [comment]
Just to follow up, recently (v1.6.1) has seen more improvements to better share memory among threads which may improve things. If you can try that, please do :)

**Comment by lahavy** [comment]
Sorry, I don't have the resources to test it anymore.

Good luck with resolving this issue
