### ISSUE TITLE
`mi_malloc_aligned` does not return aligned pointers for small-sized allocations

### ISSUE THREAD

**Issue by licheng** [microsoft/mimalloc#206]
Hi,

After the upgrade to version 1.6.0, `mi_malloc_aligned` does not always return aligned pointers for small-sized allocations.

Here is a program for test:
```c
#include <stdio.h>
#include "mimalloc.h"

int main() {
        int i;
        for (i = 0; i < 4; i++) {
                void* ptr = mi_malloc_aligned(8, 16);
                printf("%p %d\n", ptr, (size_t)ptr % 16);
        }
        return 0;
}
```
Output:
```
0x53bda001100 0
0x53bda001108 8
0x53bda001110 0
0x53bda001118 8
```

I expect all pointers are aligned by 16-bytes, but some of them are 8-bytes aligned.

After some debugging, I found the problem may be caused by commit 4531367de2bf551d5912bb612fd6b0c59a5bf849 :
```c
static void* mi_heap_malloc_zero_aligned_at(mi_heap_t* const heap, const size_t size, const size_t alignment, const size_t offset, const bool zero) mi_attr_noexcept {
  // note: we don't require `size > offset`, we just guarantee that
  // the address at offset is aligned regardless of the allocated size.
  mi_assert(alignment > 0 && alignment % sizeof(void*) == 0);

  if (alignment <= MI_MAX_ALIGN_SIZE && offset==0) return _mi_heap_malloc_zero(heap, size, zero);
```
If `alignment` <= 16 bytes, the function `_mi_heap_malloc_zero` is called without alignment requirement. But It seems `_mi_heap_malloc_zero` does not always return a pointer aligned by `MI_MAX_ALIGN_SIZE`.

I'm not sure if I understand correctly. Is this a bug?

Thanks.

**Comment by daanx** [comment]
Ah that is right. I think I should perhaps revert this commit...  The reasoning is twofold:
1. Since no platform has more strict alignment requirements than `sizeof(void*)` for allocations up to `sizeof(void*)` it should always be ok to align to `sizeof(void*)` for those, and,
2. The [`aligned_alloc`](https://en.cppreference.com/w/c/memory/aligned_alloc) specification says the size should always be an "integral multiple" of the alignment -- so, specifying an alignment larger than the requested size makes no sense.

However, I can also see that if one explicitly calls `mimalloc_aligned`, you better get an aligned pointer no matter what :-)  Let me ponder it a bit more, but I think I will revert back to the old behavior (which always return aligned pointers)

**Comment by licheng** [comment]
Ah I see. Thank you for your reply!

My original program uses `memalign` to allocate memory on Linux. I use `LD_PRELOAD` to get it overrided. The `memalign` in `mimalloc` finally routes to `mi_heap_malloc_zero_aligned_at`.

The [`memalign`](https://linux.die.net/man/3/memalign) does not have the restriction like `aligned_alloc`. So maybe we could consider keep the old behavior for those overridings?

**Comment by daanx** [comment]
I reverted to the old behavior :-) Now aligned allocation should always respect the requested alignment (even if it is larger than the requested size).

**Comment by degski** [comment]
@daanx Seems better, otherwise, the only way to align something to a cache line is to align the objects themselves, if the 'objects' are int's you waste a lot of space this (the old) way, as the int's become 64-bytes each.
