### ISSUE TITLE
Can there be a memory leak if all frees are done by other threads?

### ISSUE THREAD

**Issue by SiddheshRane** [microsoft/mimalloc#214]
I have thoroughly read the mimalloc paper and have the above design question.

Suppose thread A `malloc`s objects and then passes all of them to another thread B which `free`s them.
Thread A performs no more allocations; it might stay dormant or exit. Thread B has only modified the `thread free` list or `thread delayed free` list, but no memory has been unmapped or returned to the OS. 

Is this scenario handled? Or is there not a necessity to handle it?

**Comment by daanx** [comment]
Hi @SiddheshRane, good question, but no easy answers :-)  

Here is how it basically works:
- In mimalloc each thread has its own heap and no other thread can allocate or free in there: the only thing other threads (B) can do is add blocks to the page's `thread_local_free` list and the heap's `thread_delayed_free` list -- on each page, other threads will add first to the owning heap's thread (A) delayed free list, and after that to the page local one for performance.
- It is guaranteed that every so many allocations, the owning thread (A) enters the "slow path" (`mi_generic_alloc`) and it will go through the heap delayed free list and free all those objects and collect also the page local `thread_local_free` objects when needed.
- When pages are freed, they can be "reset" (and the physical memory reused by the OS for other threads), and when segments are freed the segments can migrate between threads efficiently.

So, as long as (A) does allocation, all objects will be freed, but if (A) is completely dormant as in your example, say blocked on a mutex, then the objects are not freed until (A) allocates again.

Now, that sounds bad, but consider what "freeing" means: on the mimalloc level it just adds blocks
to a list. Generally, memory does not get "unmapped" or returned to the OS: since all memory is virtual there is no point.  Now, when a whole page of objects becomes "free", mimalloc _does_ do a delayed "reset" of the memory which makes the physical memory available for other threads/processes but this is mostly there to reduce "virtual" fragmentation -- it flags to the OS that the memory is no longer used and does not need to go the swap space under memory pressure. Moreover, once a segment of pages becomes free, mimalloc will migrate segments very efficiently between threads (and they allocate/free from a common pool of segments). 

So, your example would not do well on mimalloc; however, in practice most of the time threads keep doing useful work or terminate (in which case the segments migrate to other threads). A work-around for your example is to explicitly call `mi_collect()` before the thread goes dormant to collect any outstanding frees (or go dormant for short periods and periodically call `mi_collect()`. )

I wish there was a way to handle this example automatically but I think there is a real tension with scalable performance here: the only way for your example to have the deallocation happen while (A) is dormant is to allow (B) threads to deallocate in (A)'s heap which would require a lock on each malloc/free; there is no easy way around this I think.

**Comment by SiddheshRane** [comment]
Hi @daanx, Thanks for the response.

Definitely, providing an API like `mi_collect()` to the user is the most straightforward and best approach.

For automatic handling, I don't have a very practical solution. I believe thread (B) can interrupt thread (A) when (B) sees that a page or segment is free. I understand there are costs of kernel context switches and conflicts with applications use of any signal. But I believe threads should be like objects in Smalltalk, communicating via messages. Plus, I believe in the cult of [exokernel](https://en.wikipedia.org/wiki/Exokernel)

But in cloud applications, there is a new concept of compiling the application with a lightweight kernel called unikernel which exposes virtualized hardware functionality such as paging and interrupts. Using interrupts might be efficient in this scenario. That's more of research topic though.

Best Regards
Siddhesh
