### ISSUE TITLE
Some questions about mmap alignment and address hint

### ISSUE THREAD

**Issue by choleraehyq** [microsoft/mimalloc#215]
Hi dear mimalloc developers, I've got some questions about mmap usage in mimalloc when I read its codes.

First, Is there any reference about this comment? https://github.com/microsoft/mimalloc/blob/6e1ca96a4965c776c10698c24dae576523178ef5/src/os.c#L398-L399

Second, why do we want an 4MiB aligned address here? Is there any performance issue around this?
https://github.com/microsoft/mimalloc/blob/6e1ca96a4965c776c10698c24dae576523178ef5/src/os.c#L403

Thanks in advance.

**Comment by daanx** [comment]
Hi @choleraehyq , good questions. What do you mean for a "reference"? It is not a published result I think, (and I think I have not seen it used before in other allocators?). Here is how it works: on some OS's, reserving 4MiB aligned memory is not efficiently supported -- on 64-bit systems what you can do is pick a random virtual address that is 4MiB aligned and try to reserve that range with `mmap` (or equivalent). In mimalloc [`mi_os_get_aligned_hint`](https://github.com/microsoft/mimalloc/blob/6e1ca96a4965c776c10698c24dae576523178ef5/src/os.c#L398) does that. It is still a hint -- if the reserving fails it will fall back to the slow path (usually overallocating by 4MiB and align in there). 

Now, it would be even nicer if we didn't need the aligned allocation in the first place.  Why is it needed? Well, when we free a pointer in the malloc interface as `free(p)` we need to find the meta-data of `p` (efficiently!) -- i.e. what mimalloc page it belongs to so we can add it to the free list. There are various ways to do this:

0. A common technique is to put header fields at `(void**)p - 1` and get the metadata from there. This can increase memory usage by a lot though (i.e. for `void*` sized objects you double the memory required) (and it is hard to make this secure)
1. Some allocators maintain a global array with, say, 1 page pointer per,  say, 4MiB or 64KiB pointing to the metadata for pointers in that range. This is good solution too and may work for mimalloc as well. Early experiments did not always work well though; problems include that on systems without over-commit, and 32-bit systems, we cannot just use a giant array that is committed on demand and we need a hierarchical structure of nested arrays much like TLB's which makes `free` slower. The advantage of this is that we can put the metadata at a completely different location. Still considering this design as well.
2. Another technique on 64-bit systems is to allocate different size-classes in different memory areas and use lookup arrays per area.
3. ... and I guess there are many more tricks that can be applied.
4. But mimalloc uses alignment: it always aligns on 4MiB boundaries and promises that any object in there starts within the first 4MiB. Then we can simply mask the bottom 20 bits of a pointer to get the (`mi_segment_t`) meta-data for a pointer `p` as `p & (~(4*MiB - 1))`. (and from there the mimalloc page).
5. A bad part of (4) is that it locates metadata in front of the user data; in secure mode it is surrounded by guard pages, but we can imagine doing a design where we still use alignment but put the metadata in a "mirror" area in the vast 64-bit virtual address-space, something like ``mirror_base + (p & (~(4*MiB - 1)))`. 

Hmm, I may have misunderstood your question now that I read it again :-) You may be wondering why we return 4MiB aligned blocks on the OS level; well, that is just because we only use the aligned calls for aligned segments so the hint code just tries that alignment. Simple is good :-)

**Comment by choleraehyq** [comment]
@daanx Thanks for your response!
Sorry about my poor English, which leads to your misunderstanding. My first question is about "we can do efficient aligned allocation by using the 4TiB to 30TiB area to allocate them", I wonder why can we do allocation efficiently using this specific area (4TiB to 30TiB)? What's the difference between 0-4TiB and 4TiB-30TiB?

Your response perfectly answers my second question, thanks!

**Comment by daanx** [comment]
Ah, there is nothing special about the 4TiB to 30TiB area :-)
Just trying to allocate outside the initial 4TiB to make `mimalloc` pointers easy to spot in the debugger and trying to stay under 64TiB as that is the usual limit now for 64-bit OS's (46 bits of the current 48 available; 1 for kernel, and 1 for direct physical mapping).  Also, mimalloc uses the area above 32TiB for huge OS page allocations which are fixed so our regular allocations should stay under the 32TiB, therefore we use the 4 - 30TiB area starting at a random spot in `release` and `secure` mode (using 20 bits of randomness the start area is 4MiB aligned in the initial 4 to 8TiB area).

**Comment by choleraehyq** [comment]
Thanks!
