### ISSUE TITLE
mi_register_output doesn't work on mimalloc 1.1

### ISSUE THREAD

**Issue by santagada** [microsoft/mimalloc#307]
Hi,

I know 1.1 is an old release, but did anyone tried overriding mimalloc to ouput to OutputDebugString in windows?

I tried overriding by simply calling it mi_register_output(OutputDebugStringA); during an object construction but it seems to be already too late as I see output on the console but not on anything that grabs those debug strings (debugview++ or visual studio).

Is there any documentation on where to call this function? Its weird that for jemalloc this mostly works.

**Comment by daanx** [comment]
Hi @santagada ,  sorry for the late reply. Uh, v1.1 is really old -- this is probably resolved by now. 
I remember doing good output is quite tricky when overriding `malloc` on Windows; when loading the `malloc` calls are redirected very early before even the C runtime is loaded so we cannot use `printf` for example, and the `mi_register_output` call has not happened yet either. What mimalloc does in later versions is cache all early output (I think up to 8k or something) and when you register all cached output is sent to the newly registered output hook at that time. I don't think this was in place at v1.1 though so that is why you may see really early output in the console but not in your registered output function.
