### ISSUE TITLE
Visual Studio /analyze warnings

### ISSUE THREAD

**Issue by jasongibson** [microsoft/mimalloc#311]
The VS /analyze output had a lot of noisy-looking stuff to say, but there were
a couple that seemed like they were worth looking into.

  - mimalloc\os.c(700) : warning C6250: Calling 'VirtualFree' without the MEM_RELEASE flag might free memory but not address descriptors (VADs).  This causes address space leaks.

The os_page_size shadow is because it's compiling as a single file:

  - mimalloc\segment.c(201) : warning C6244: Local declaration of 'os_page_size' hides previous declaration at line '73' of 'c:\mimalloc\os.c'.: Lines: c:\mimalloc\os.c:73

A couple others:

  - mimalloc\segment.c(382) : warning C6285: (<non-zero constant> || <non-zero constant>) is always a non-zero constant.  Did you intend to use the bitwise-and operator?
  - mimalloc\page.c(712) : warning C6237: (<zero> && <expression>) is always zero.  <expression> is never evaluated and might have side effects.
 - mimalloc\heap.c(246) : warning C6011: Dereferencing NULL pointer 'heap'. See line 238 for an earlier location where this can occur: Lines: 228, 231, 237, 238, 239, 244, 245, 246

This is with v1.6.4.

**Comment by daanx** [comment]
Hi Jason, 

Hi Jason, this is great!  Thanks

> * mimalloc\os.c(700) : warning C6250: Calling 'VirtualFree' without the MEM_RELEASE flag might free memory but not address descriptors (VADs).  This causes address space leaks.

This warning is wrong for us: we use VirtualFree to specifically decommit memory here (not to free the address range). 
So, the code is good :-)  [msdn](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualfree)
 
> The os_page_size shadow is because it's compiling as a single file:

Ah, that one is fixed already in the latest versions.

> * mimalloc\segment.c(382) : warning C6285: ( || ) is always a non-zero constant.  Did you intend to use the bitwise-and operator?
> * mimalloc\page.c(712) : warning C6237: ( && ) is always zero.   is never evaluated and might have side effects.

These two are due to testing the  `MI_SECURE` macro which is `0` usually. I guess we could wrap the `if` condition in an `#ifdef` to circumvent this warning. I will try this out if it doesn't clutter the code too much :-)

> * mimalloc\heap.c(246) : warning C6011: Dereferencing NULL pointer 'heap'. See line 238 for an earlier location where this can occur: Lines: 228, 231, 237, 238, 239, 244, 245, 246

Right -- I can see it has an assertion that `heap != NULL`  but we could just as well test for and avoid trouble. I will add extra non NULL checks there. Thanks!

**Comment by jasongibson** [comment]
Thank you for taking a look and for the changes.
Here's the code to suppress the VirtualFree() warning in Visual Studio, should that be worth doing.

```
# pragma warning( push )
# pragma warning( disable : 6250 )
    BOOL ok = VirtualFree(start, csize, MEM_DECOMMIT);
# pragma warning( pop )
```
