### ISSUE TITLE
Malloc leak detection

### ISSUE THREAD

**Issue by nmoinvaz** [microsoft/mimalloc#35]
This issue is for a feature request to support basic C leak detection. I'm aware that CRT has leak detection, however that is Windows only. I would imagine something similar to:

https://stackoverflow.com/questions/9074229/detecting-memory-leaks-in-c-programs

That prints the allocs that have not been freed and their line and filename at the end of the application when it is done.

**Comment by cloudhan** [comment]
I would suggest you use AddressSanitizer to do the job.

**Comment by nanokatze** [comment]
There are lots of tools to already do leak detection: valgrind, asan, other mallocs, libgc. Why does mimalloc need to take this responsibility?

**Comment by santagada** [comment]
Mimalloc already has all the tools for this, you can do a heap walk right before the main thread exits... all non free pages should have migrated to the main heap IIUC the code. So just walking through all the main thread heap with an atexit handler should work. Have you tried that @nmoinvaz ?

**Comment by Kamayuq** [comment]
For small leaks an at exit handler is not really useful. One does need to have start stop functionality when the app is running as otherwise those small leaks might be hidden by a high watermark on launch. Also leaks might be hidden inside other containers and arrays (like caches) that are properly cleaned up on exit but will accumulate while the app is running.
