### ISSUE TITLE
WebAssembly support?

### ISSUE THREAD

**Issue by jedisct1** [microsoft/mimalloc#4]
Is WebAssembly a target mimalloc may eventually support?

WebAssembly doesn't have `mmap()`; only a single, linear memory segment that can grow. Allocating memory from the host must be done in a way similar to `sbrk(2)` as in the good old days.

Is it something `mimalloc` could do?

**Comment by daanx** [comment]
Yes, we want to see a WASM backend (especially since I am working towards supporting algebraic effects in WASM). I didn't study the full implications yet, but in principle it should be quite easy to extend mimalloc to use an `sbrk` like interface. The <https://github.com/microsoft/mimalloc/blob/master/src/os.c> source contains the OS interface but basically mimalloc just gets 4MiB chunks from the OS using whatever is available. Of course, some functionality would become noops, like guard pages or page resets, but that makes sense in a WASM environment.

**Comment by jedisct1** [comment]
Preliminary port to WebAssembly/WASI here: https://github.com/jedisct1/mimalloc

**Comment by daanx** [comment]
That is crazy fast! I'll look at it later when I have more time but this is great :-)

**Comment by daanx** [comment]
I'll close this now that there is a pull request #32
