### ISSUE TITLE
Shockingly bad performance of libc-bench with mimalloc LD_PRELOAD'ed

### ISSUE THREAD

**Issue by Logarithmus** [microsoft/mimalloc#431]
Hello, I've run [`libc-bench`](https://www.etalabs.net/libc-bench.html) (set of benchmarks for libc) and was shocked by poor results of `mimalloc`. `mimalloc` performed much worse than `glibc`'s system allocator. And surprisingly `mimalloc`'s results are also worse than of `musl`, which is known for its poor allocator.
See results: https://gist.github.com/Logarithmus/f45b36eb7ed7fccdb851bce5bd37c913

**Comment by daanx** [comment]
Ouch -- that is disappointing; but also hopeful :-) as perhaps it can lead to further improvements once we understand what is the cause of this. 

It is surprising too -- the mimalloc benchmarks are wide ranged and mimalloc is always faster than the system allocators and similar to tcmalloc/jemalloc in many others. It is also used in very large services (using tens of thousands machines) where it offers significantly better performance and memory behavior. So it is surprising to see it do worse in that set of benchmarks; some things come to mind:

- all benchmarks run in a very short time (many under 0.1s) so startup may be a factor; mimalloc gets numa information on Linux which may be slow. Perhaps run with `MIMALLOC_USE_NUMA_NODES=1`? (there may be other such things not sure, perhaps `MIMALLOC_EAGER_REGION_COMMIT=0` ?
- maybe preload is a factor and using direct overrides (by including `mimalloc-override.h` in all sources) may help . 
- maybe some os-call we make on Linux happens to cause a higher startup cost? 

Anyway, it would be great to include these benchmarks in [mimalloc-bench](https://github.com/daanx/mimalloc-bench); perhaps you can try to do that and send a PR  there? 
That way I can also easily test locally and confirm the results and see what is the cause.    

I do not have much time in July with vacation and seminars but after that I would like to investigate this further.

**Comment by Logarithmus** [comment]
@daanx sorry for offtopic, but can you take a look at my PRs: #427, #428, #429?

**Comment by daanx** [comment]
I looked at the `libc-bench` you linked to above, and ran the benchmarks on Ubuntu 20.04 with an AMD5950X. Well, the benchmark sizes are much too small and run in under 0.01s for example, so I added iterations so each of the tests runs in ~1s; then, it turns out to fork the whole process for each of the ~20 tests (ouch!) so I removed this as well and ran all tests as one run without output; then:
```
sys: 1.30s, 142mb rss
jemalloc: 1.31s, 143mb rss
mimalloc: 1.30s, 143mb rss
```
(Surprising to see so little difference here; I guess the allocation is too easy or there is too much other work that dominates.). 

Thanks for the pointer again, but as you can see, benchmarking allocators is a tricky business and micro benchmarks are not that great. It is all about real-world performance in the end and many allocators try to optimize for that; for example, mimalloc has lots of work done to avoid memory fragmentation on long running services that use huge working sets (> 100GiB). Nothing in these kinds of microbenchmarks will show any of that.
