### ISSUE TITLE
can not build mimalloc

### ISSUE THREAD

**Issue by mmongiacmu** [microsoft/mimalloc#549]
Hello All,

When building mimalloc using the standard instructions
<img width="1033" alt="Screen Shot 2022-02-17 at 10 54 26 PM" src="https://user-images.githubusercontent.com/72166901/154955061-711c1fd3-21e7-4641-a6c7-c69d719dfe93.png">
, i get the following error (attached). Does anyone know what the issue could be?

**Comment by mmongiacmu** [comment]
i am using macversion 10.13.6

**Comment by devnexen** [comment]
Little suggestion, in src/random.c, does it solve your build issue if you add the following :

`#include <CommonCrypto/CommonCryptoError.h>`

on top of

`#include <CommonCrypto/CommonRandom.h>`

?

**Comment by devnexen** [comment]
nope :) which version of Xcode are you using ?

**Comment by mmongiacmu** [comment]
i believe it's Xcode 8.3.3!

**Comment by mmongiacmu** [comment]
If i type man alligned_alloc into terminal, i get "No manual entry for aligned_alloc"!

**Comment by devnexen** [comment]
yes it s old version and yes I expected you did not get an entry. if you comment the `MI_INTERPOSE_MI(aligned_alloc)` line it should build (of course it deserves a real fix).

**Comment by mmongiacmu** [comment]
thank you very much my friend. im sorry could i ask you 2 more questions? is it easy to to update to a later xcode version? i tried via the apple store and said i could only update if i had mac os 11.0 or later. but it seems its not possible to update from 10.13 to 11? 

number 2 i am actually using rust and running cargo clippy and getting the following error. is there any hack to get rid of this error?
<img width="1673" alt="Screen Shot 2022-02-21 at 12 15 50 PM" src="https://user-images.githubusercontent.com/72166901/155001550-01ee2ab7-27a3-4d8a-b926-65c24ac754c7.png">

**Comment by rob-p** [comment]
I just wanted to chime in here with a related issue.  We use `bioconda` for distribution of our software on linux and OSX, and recent versions of mimalloc do not build under their OSX configuration.  Specifically, we're seeing the same error initially posted here.  You can find the specific build-log lines [here](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=11980&view=logs&j=3e927886-88a5-5ae4-09f7-f53fa1a22322&t=577c9198-bb4c-5a92-f06b-21e420caadce&l=659).  

Interestingly, however, this is a newer problem.  Previous versions (about 2 versions ago, I think) of mimalloc worked fine on this system.  The temporary fix we have in place now is to force an older version of mimalloc (actually it's installed through the libmimalloc-sys rust crate since this is a rust program), but this is obviously not an ideal situation going forward.  Is there any way that new releases can be made to compile on such a system?  In that case, the program is being compiled using `Xcode_13.2.1`.

Thanks!
Rob

**Comment by devnexen** [comment]
> thank you very much my friend. im sorry could i ask you 2 more questions? is it easy to to update to a later xcode version? i tried via the apple store and said i could only update if i had mac os 11.0 or later. but it seems its not possible to update from 10.13 to 11?
> 
> number 2 i am actually using rust and running cargo clippy and getting the following error. is there any hack to get rid of this error? <img alt="Screen Shot 2022-02-21 at 12 15 50 PM" width="1673" src="https://user-images.githubusercontent.com/72166901/155001550-01ee2ab7-27a3-4d8a-b926-65c24ac754c7.png">

I have no real idea honestly how to make that big leap in term of macOs releases, I personally update incrementally.

Regarding your last issue, so what happens if we just follow the compiler advice ? if this work I ll update my PR accordingly

ie changing the line 489 in src/alloc.c with

`if (mi_likely(tid == mi_atomic_load_relaxed((_Atomic(mi_threadid_t)*)&segment->thread_id) && page->flags.full_aligned == 0)) {`

**Comment by mmongiacmu** [comment]
Hi devnexen,  appears all i had to do was force an older version of libmimalloc-sys and things started working smooth as leather! 

thank you for being so kind! usually my experience on these type of things is a lot more cold!

hope you are well!

**Comment by devnexen** [comment]
thanks @rob-p @mmongiacmu for your reports, @daanx will decide how to deal with this.

**Comment by daanx** [comment]
Hi all, thanks for the reports; Thanks @devexn for the PR!  I think the latest `dev` and `dev-slice` branches should fix these build issues (can you check this @rob-p ?).
