### ISSUE TITLE
/fsanitize=address & mimalloc

### ISSUE THREAD

**Issue by claimred** [microsoft/mimalloc#562]
Hello

I am struggling to understand how to properly use msvc AddressSanitizer together with mimalloc. 🤔  My understanding is that one should provide some sort of API functions for that to work. Perhaps there is an example somewhere or part of the documentation that I am missing?

https://docs.microsoft.com/en-my/cpp/sanitizers/asan-runtime?view=msvc-170#custom-allocators-and-the-addresssanitizer-runtime

Thanks!

**Comment by daanx** [comment]
Apologies for the late reply; mimalloc does not work with an address sanitizer as these typically use their own special allocator to keep track of all kinds of metadata. So, for debugging just enable the address sanitizer without using mimalloc, and use mimalloc for release versions.

ps. Having said that,  we are working on creating builds of mimalloc that work with Valgrind (and perhaps others in the future), and there is an experimental branch of mimalloc (`dev-slice-trace`) that can find heap block overflow errors.

**Comment by claimred** [comment]
Thanks for the answer! The thing is Microsoft docs suggests that there is an API to add custom allocator support for their sanitizer if I am reading things correctly. What I am struggling with is that I don't understand how to use it. Perhaps you could have a look?

>The compiler is unable to automatically add shadow-memory management calls to a custom allocator. It's the user's responsibility to use the [provided manual poisoning interface](https://docs.microsoft.com/en-my/cpp/sanitizers/asan-runtime?view=msvc-170#poisoning). This API enables these allocators to function properly with the existing AddressSanitizer runtime and [shadow byte](https://docs.microsoft.com/en-my/cpp/sanitizers/asan-shadow-bytes?view=msvc-170) conventions.

**Comment by daanx** [comment]
Ah thanks -- yes, this is similar to valgrind. We could indeed add the right calls in mimalloc to make it work the msvc sanitizer. In particular, when memory is malloc'd we would call `__asan_unpoison_memory_region` and
when it is freed we call `__asan_poison_memory_region`. This way the sanitizer can detect an illegal access. i I will put this on the todo list (together with valgrind support) as it would require some careful consideration to add these calls at just the right places.  Also, it would still require a separate build of mimalloc due to the overhead of such calls. 

For now though, mimalloc does not work together a memory sanitizer.
