### ISSUE TITLE
error in reallocarray, introduced between 2.0.3 and 2.0.6

### ISSUE THREAD

**Issue by pg83** [microsoft/mimalloc#574]
I belive this is wrong:

```
#include <iostream>
#include <errno.h>

int main() {
    std::cerr << (size_t)realloc(0, 0) << std::endl;
    std::cerr << errno << std::endl;
    std::cerr << (size_t)reallocarray(0, 0, 16) << std::endl;
    std::cerr << errno << std::endl;
}
------
0
0
0
12
```

**Comment by daanx** [comment]
Thanks! That is a strange edge case for realloc. So, mimalloc already allows `mi_malloc(0)` and returns a non NULL pointer to a zero sized block (as allowed by the standard). This is good since a NULL result always indicates an error. 

With the patch, realloc behaves the same where a NULL result is always an error and leaves the argument pointer non-freed. Following the standard:

- if the argument p == NULL, it behaves like malloc, so `realloc(NULL,0)` returns a non NULL pointer to a zero sized block
- _otherwise_ if the new size is 0, the behavior is implementation defined: we again just reallocate to a zero sized block now returning a non-NULL pointer and free the argument pointer. (this is what is fixed now).
- now `reallocarray` behaves correctly with `errno` as only NULL signifies an error.
- note that `realloc` does _not_ set errno in mimalloc (as allowed by the standard)


Best
