### ISSUE TITLE
question: tld_stats are not updated during malloc/free operations

### ISSUE THREAD

**Issue by romange** [microsoft/mimalloc#645]
`_mi_os_commit` and `_mi_os_decommit` functions ignore the passed `tld_stats` object and instead pass _mi_stats_main that requires atomic operations. Seems like a deliberate decision - what's the reason behind that?

**Comment by daanx** [comment]
mmm, I does look intentional and I remember now it had to do something with one thread committing with other threads decommitting which made the stats look "off". It has little overhead to do an atomic operation compared to the (de)commit so I think it is fine as it is ?

---
ps. @romange: I checked your dragonfly issue; very interesting as this is one the areas where I worked hard on mimalloc to handle long running big services where most allocators tend to fragment over time (and use more and more memory).  For mimalloc, you may try the following settings to make the defragmentation more aggressive:
(in v2):

- in `mimalloc-types.h`, reduce the minimal commit size from:
  ```C
  #define MI_MINIMAL_COMMIT_SIZE      (16*MI_SEGMENT_SLICE_SIZE) 
  ```
  to `MI_SEGMENT_SLICE_SIZE`  -- allows much more fine-grained commit/decommit at the cost of more OS calls.
- in `mimalloc-types.h`, reduce the slice size from:
  ```C
   #define MI_SEGMENT_SLICE_SHIFT            (13 + MI_INTPTR_SHIFT)
  ```
  to ` (12 + MI_INTPTR_SHIFT)` -- smaller pages increase the likelihood they get completely free.
- set the option `mi_option_decommit_extend_delay` to `1` or `0` -- this make decommit more aggressive (and same for the `mi_option_decommit_delay` lowering it to `10` or `5`, or even `0`). This comes at the cost of more OS calls (and that can add up depending on the workload).

Now, all of the above do not handle the exact case you described where in a single "mimalloc page" we allocate to almost full, and the deallocate most; currently mimalloc will not try to "reset" the memory in-between the blocks inside such page. Nevertheless, the above options may get you close depending on the workload.

**Comment by romange** [comment]
Thanks for the tips @daanx. Yeah, I understand the problem with accounting commit stats per thread.
Due to our shared-nothing architecture, we maintain heap per thread but even in this case I am not sure we always free pointers in the same thread, so we may also run into the same issues. 

Having said that, applications that do succeed to only malloc and free per each thread, may need  better introspection into how their "rss" or "comitted" per thread is different from their "used" memory.
