### ISSUE TITLE
mimalloc: assertion failed in mi_segment_span_free_coalesce

### ISSUE THREAD

**Issue by colesbury** [microsoft/mimalloc#691]
I'm using mimalloc v2.0.9. I'm getting an assertion error when I do the following:

1. Allocate a large block of memory from thread 1 (i.e., requiring an MI_SEGMENT_HUGE).
2. Thread 1 exits, abandoning the segment.
3. The block of memory is freed from thread 2.
4. Thread 2 exits

```c
#include <assert.h>
#include <pthread.h>
#include <mimalloc.h>

static char* ptr;

static void* thread1_allocate(void *_unused)
{
  ptr = mi_malloc(22085632);
  return NULL;
}

static void* thread2_free(void *_unused)
{
  assert(ptr);
  mi_free(ptr);
  ptr = NULL;
  return NULL;
}

int main(int argc, char** argv) {
  pthread_t thread1, thread2;

  pthread_create(&thread1, NULL, &thread1_allocate, NULL);
  pthread_join(thread1, NULL); 

  pthread_create(&thread2, NULL, &thread2_free, NULL);
  pthread_join(thread2, NULL); 

  return 0;
}
```

```
mimalloc: assertion failed: at "/raid/sgross/mimalloc/src/segment.c":635, mi_segment_span_free_coalesce
  assertion: "segment->used == 1"
Aborted
```

**Comment by daanx** [comment]
Thanks Sam! I studied it and the assertion is indeed too strict (so no bug). It is because for v2.0.9 I made huge segments behave more regularly and no longer as abandoned "orphans" such that heap walking works correctly now for huge segments/blocks. To still release memory early for huge block frees we now decommit them directly on free but the block and segment itself is reclaimed later on like regular segments -- this lead to the now failing assertion but it is actually correct behavior now.
