### ISSUE TITLE
Alignment issue in mi_malloc_aligned when requested size = alignment (regression on dev-slice)

### ISSUE THREAD

**Issue by epoupon** [microsoft/mimalloc#700]
Hello,

We recently tried to bump mimalloc from `1.7.9` to `2.0.9`.
However we noticed a regression in `mi_malloc_aligned` when `size` = `alignment` for the following values: 256, 512, 1024 (all other values down to 8 and up to 1MB are correctly handled though).
Tests done on windows using Visual Studio 2022, MI_PADDING and MI_DEBUG are **not** set.

**Comment by Trithek** [comment]
I've just started using mimalloc, so I'm not familiar enough with the code to say for certain yet, but...
The sizes up to 128 are correct, and starting from 1024 again, so that's a factor of 8.
In mi_heap_malloc_aligned, is that supposed to say MI_SMALL_WSIZE_MAX instead of MI_SMALL_SIZE_MAX in those ifs?
That would at least solve the issue, and it'd be an easy mistake to make.

Maybe @daanx knows?

**Comment by daanx** [comment]
Wow, that was a terrible bug; :-(  Should be fixed in the latest `dev-slice` -- Thanks so much for the report!
