### ISSUE TITLE
while using `mimalloc` memory allocator, `miniupnpd` rules cannot be recognized.

### ISSUE THREAD

**Issue by enihcam** [microsoft/mimalloc#725]
repro steps:

```
$ wget https://github.com/miniupnp/miniupnp/archive/refs/tags/miniupnpd_2_3_3.tar.gz
$ cd ./miniupnpd
$ ./configure \
    --ipv6 \
    --leasefile
$ CONFIG_OPTIONS="--ipv6 --leasefile" make -f Makefile.linux config.h
$ make -f Makefile.linux
$ LD_PRELOAD=/usr/lib/libmimalloc.so ./miniupnpd -f ~/miniupnpd.conf
```
where miniupnpd.conf contains the following lines
```
allow 1024-65535 192.168.0.0/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
```

```
error:
---
Apr 05 03:32:49 miniupnpd[423]: MiniUPnP is not compiled with ENABLE_REGEX. Please remove any regex filter and restart.
Apr 05 03:32:49 miniupnpd[423]: parsing error file /etc/miniupnpd/miniupnpd.conf line 184 : allow 1024
Apr 05 03:32:49 miniupnpd[423]: Error reading configuration file /etc/miniupnpd/miniupnpd.conf
```

https://github.com/miniupnp/miniupnp/issues/652

**Comment by daanx** [comment]
I tried to repro but the build of miniupnpd fails with "unknown type name `ipct_handle_t`; did you mean `iptc_handle'"?  not sure how to fix this?
(this is on linux after install `libiptc-dev`)

**Comment by enihcam** [comment]
> I tried to repro but the build of miniupnpd fails with "unknown type name `ipct_handle_t`; did you mean `iptc_handle'"? not sure how to fix this? (this is on linux after install `libiptc-dev`)
@miniupnp

a simpler repro:
1. boot with Manjaro (or any archlinux-based) live USB
2. pacman -S miniupnpd mimalloc
3. continue.... (sorry I'm using my phone to type.)

**Comment by enihcam** [comment]
> I tried to repro but the build of miniupnpd fails with "unknown type name `ipct_handle_t`; did you mean `iptc_handle'"? not sure how to fix this? (this is on linux after install `libiptc-dev`)

try `sudo apt install pkg-config uuid-dev libiptc-dev libxtables-dev`

**Comment by daanx** [comment]
I did `sudo apt install miniupnpd` on Ubuntu Linux ( 2.2.3, Oct 3 2021)
When I run
```
LD_PRELOAD=./libmimalloc-debug.so miniupnpd -f ./miniupnpd.conf
```
(using the latest `dev` branch build in debug mode, with your conf provided above)
it says that option `-i` and `-a` are missing? If I add those:
```
LD_PRELOAD=./libmimalloc-debug.so miniupnpd -f ./miniupnpd.conf -a 192.168.0.1 -I 192.168.0.1
```
nothing happens (it seems it just loads the deamon fine?). 
I cannot repro with `dev-slice` either. I guess that you have a global conf file as well that contains more? Or maybe using a different version?  If you can find repro steps on a clean Ubuntu 22 that would be great.  Thanks again.
```

**Comment by enihcam** [comment]
@daanx @miniupnp

```bash
~ $ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"

~ $ ./miniupnp/miniupnpd/testupnppermissions "allow 1024-65535 192.168.0.0/24 1024-65535"
 1 'allow 1024-65535 192.168.0.0/24 1024-65535'
Permission read successfully
allow 1024-65535 192.168.0.0/255.255.255.0 1024-65535

~ $ LD_PRELOAD=./mimalloc/out/debug/libmimalloc-debug.so ./miniupnp/miniupnpd/testupnppermissions "allow 1024-65535 192.168.0.0/24 1024-65535"
 1 'allow 1024-65535 192.168.0.0/24 1024-65535'
MiniUPnP is not compiled with ENABLE_REGEX. Please remove any regex filter and restart.
Permission read failed, please check its correctness
```

**Comment by daanx** [comment]
Ah, that took some time to investigate. I did not have `testupnppermissions` as I cannot build upnpd (due to the `iptc_handle_t` issue...). But I could build just the `testupnppermissions` program and test with the installed miniupnpd :-) and reproduce the problem. After more debugging, it seems miniupnp does a `token = realloc(token,i)` where `i` is zero ..  (`upnppermissions.c:155`).   Then, later, the pointer is dereferenced and tested (`perm->re[0] == '\0'`).  Now, the C standard for a zero reallocation says:

_If the size of the space requested is zero, the behavior is implementation-defined: either a null pointer is returned, or the behavior is as if the size were some nonzero value, except that the returned pointer shall not be used to access an object_
([link](https://stackoverflow.com/questions/16759849/using-realloc-x-0-instead-of-free-and-using-malloc-with-length-of-a-string)) and I think in C++ it is even undefined.

So, I think this is a bug in miniupnpd.  Mimalloc always returns a pointer on a zero-sized (re)allocation. This way, realloc(p,0) always only returns NULL on an error where `p` is not freed. 

I added a patch to mimalloc to zero initialize the first byte of a zero sized reallocation which fixes the error with miniupnpd -- but I think going forward miniupnpd should not rely on this behavior of realloc. 

Can you try with the latest `dev` or `dev-slice` branch if this fixes the errors for you as well?

**Comment by enihcam** [comment]
@daanx thanks a lot! i was about to add more details for repro of the issue. :)

Yes, the patch works:
```bash
$ LD_PRELOAD=../../mimalloc/out/debug/libmimalloc-debug.so ./testupnppermissions "allow 1024-65535 192.168.0.0/24 1024-65535"
 1 'allow 1024-65535 192.168.0.0/24 1024-65535'
Permission read successfully
allow 1024-65535 192.168.0.0/255.255.255.0 1024-65535
```

cc @miniupnp https://github.com/miniupnp/miniupnp/issues/652

In one way I agree `miniupnpd` needs to address this issue according to your root cause analysis. On the other hand, I believe `miniupnpd` is one of many existing applications for which `mimalloc` needs to keep backward compatibility. What do you think?

Again, thanks for help.

**Comment by daanx** [comment]
Thanks -- yes, I will keep the patch in mimalloc for backward compatibility -- really great that you found this one as I would like mimalloc to be a full replacement :-)
(but miniupnp should probably not rely on this behavior in general though as any future allocator may not guarantee this.)

**Comment by daanx** [comment]
The latest release contains the fix now. Thanks again.
