### ISSUE TITLE
Perf regression

### ISSUE THREAD

**Issue by mvparakhin** [microsoft/mimalloc#920]
Just tried to update from 2.0.7 to 2.1.7 - a dramatic performance regression (20x) in the situation when many threads on AMD EPYC are simultaneously parsing a huge file, allocating lots of small memory chunks. Unfortunately, I don't have the bandwidth to isolate and debug, but wanted to let you know. Rolling back to 2.0.7 gets the perf back.

**Comment by mvparakhin** [comment]
Oh, this is under Windows 11, VS2022 (17.10.5), release build, no ASAN or anything.

**Comment by daanx** [comment]
Yikes -- that is not good. It is interesting as we don't see that regression in our standard benchmarks (mimalloc-bench). It would be good to figure out what the cause is -- can you share your benchmark?

If not, can you perhaps try some experiments so we might figure out what is causing this. It might be the new strategy of reclaiming abandoned segments on a free -- could you try running your benchmark with 2.1.7 with the environment settings:
```
MIMALLOC_ABANDONED_RECLAIM_ON_FREE=0
MIMALLOC_VERBOSE=1
```
(the verbose setting will show if the setting abandond_reclaim_on_free is correctly picked up).  

This is a guess of course but let's see.

**Comment by daanx** [comment]
Just to add: another potential thing to try (on windows) is to set:
```
MIMALLOC_EAGER_REGION_COMMIT=1
```

**Comment by mvparakhin** [comment]
Sure, happy to help. Will do and report back. It's just really a lot of work to isolate the self-contained small benchmark, as the system is huge, but I can run whatever you need on my end. Let me try those switches.

**Comment by mvparakhin** [comment]
The second does it! MIMALLOC_EAGER_REGION_COMMIT=1 makes everything fast - again, dramatic difference, more than 20x. Abandoned reclaim has no effect.
By the way, with the region commit set, verbose mode shows a warning: environment option "mimalloc_eager_region_commit" is deprecated -- use "mimalloc_arena_eager_commit" instead.

**Comment by daanx** [comment]
Ah great to hear! Well, but also strange it regressed so much compared to 2.0.7. I'll look into the cause of this and see if we can change things.

**Comment by mvparakhin** [comment]
Thank you! Let me know if I can help. You folks are awesome, on Windows mimalloc is clearly the best allocator bar none, we really hope you continue developing it.

**Comment by daanx** [comment]
Thank you for your kind words :-).
