### ISSUE TITLE
[dev] Mingw Windows compilation GetPhysicallyInstalledSystemMemory Error

### ISSUE THREAD

**Issue by RealVarHar** [microsoft/mimalloc#976]
Hi,
Im using windows, mingw, gcc/clang from winlibs.com to be exact.
Ive noticed that on my machine
main branch was building, 
but dev was not building,
    due to error call to undeclared function 'GetPhysicallyInstalledSystemMemory';
Please replace CMakeLists.txt line
if(MINGW)
  add_definitions(-D_WIN32_WINNT=0x600)
endif()

with 

if(MINGW)
  add_definitions(-D_WIN32_WINNT=0x601)
endif()

as mingw has a bit different legacy settings and treats this function as avaliable since win7, not Vista.
This >>should<< not break anything with other ways of windows builds, in the worst case it will abandon Vista support
(Apologies this is not a Pull request)

**Comment by imsharukh1994** [comment]
Modify CMakeLists.txt
Open your CMakeLists.txt file: This file should be in the root directory of your project. It contains the build configuration for your project, including platform-specific settings.

Find the block that checks for MinGW: Look for a section in CMakeLists.txt that looks like this:

cmake
Copy code
if(MINGW)
    add_definitions(-D_WIN32_WINNT=0x600)
endif()
This block sets the minimum Windows version to Windows Vista (0x600). The issue arises because the function GetPhysicallyInstalledSystemMemory is only available in Windows 7 and later, so you need to update the version check.

Update the _WIN32_WINNT value: Modify the value from 0x600 (Vista) to 0x601 (Windows 7). The updated block should look like this:

cmake
Copy code
if(MINGW)
    add_definitions(-D_WIN32_WINNT=0x601)
endif()
This tells the compiler that the minimum supported Windows version is Windows 7, which will make the GetPhysicallyInstalledSystemMemory function available during the build.

Save the file: After making the change, save the CMakeLists.txt file.

Rebuild your project: Run your build process again (for example, using cmake and make or through an IDE like CLion or Visual Studio Code). This should resolve the error related to the undeclared function.

Why this works:
What _WIN32_WINNT=0x601 means:

The macro _WIN32_WINNT defines the minimum version of Windows that your application supports.
0x600 corresponds to Windows Vista.
0x601 corresponds to Windows 7.
By setting _WIN32_WINNT=0x601, you're telling the compiler that you're targeting at least Windows 7, where the GetPhysicallyInstalledSystemMemory function is available.

Impact:

This change will not affect any other builds targeting newer Windows versions (like Windows 8, 10, or 11), as they support this version of the Windows API.
The only downside is that your project will no longer support Windows Vista. However, Windows Vista has reached its end of life, and most modern software no longer targets it.
Conclusion:
Open CMakeLists.txt.
Modify the if(MINGW) block to use 0x601 instead of 0x600 for _WIN32_WINNT.
Save the file and rebuild the project.

**Comment by daanx** [comment]
Thanks!

**Comment by RealVarHar** [comment]
@dscho looks like something like this is already implemented in the dev branch, and compiles succesfully with add_definitions(-D_WIN32_WINNT=0x600),  though i did not check on windows vista yet to make sure it works

**Comment by dscho** [comment]
@RealVarHar I fear that I already mentioned what you're referring to:

> (instead of [095f848](https://github.com/microsoft/mimalloc/commit/095f848ae85b57fd0d478b2db150cf1821bbde47))

That commit forces `_WIN32_WINNT=0x0601`, which correpsonds to Windows 7. So it will distinctly not work with Vista and you do not even have to check.

**Comment by daanx** [comment]
Hi @dscho  -- we do define now `-D_WIN32_WINNT=0x601` (in the cmake file) -- but also we don't check for it as we also use a dynamic check now for the get physica memory call.  Do you think we should remove the define as well, or is it ok to leave it ?

**Comment by dscho** [comment]
> Hi [@dscho](https://github.com/dscho) -- we do define now `-D_WIN32_WINNT=0x601` (in the cmake file) -- but also we don't check for it as we also use a dynamic check now for the get physica memory call. Do you think we should remove the define as well, or is it ok to leave it ?

@daanx my problem is that I need to vendor in `mimalloc`'s source code in Git for Windows, therefore that CMake-based change won't have any effect, and a compile error is the consequence. That's why I would really like to make the change in `mimalloc`, so that Git for Windows does not have to deviate too much from regular `mimalloc`.

**Comment by daanx** [comment]
@dscho , ah I didn't realize this would cause a compile error. So, it seems we should just remove the definition from the CMakeFile (since we check dynmaically anyway). Or should we use `-D_WIN32_WINNT=0x600` ?

**Comment by dscho** [comment]
Oy! @daanx I totally missed that you had already done in 5e71dfc33641bbf2853e9a64825fcd02bb8c95a3 what I proposed in https://github.com/microsoft/mimalloc/issues/976#issuecomment-2700719034, sorry about that!

For the record, I got the compile error with v2.1.9, which lacked that change... sorry for the noise!
